<<<<<<< HEAD
// prisma.config.ts
// Configurazione compatibile con Prisma 4+
// Non serve più importare defineConfig da "prisma/config"

import { PrismaClient } from "@prisma/client";

// Usa process.env.DATABASE_URL per rendere la configurazione compatibile con sviluppo e produzione
const prisma = new PrismaClient({
  datasources: {
    db: {
      url: process.env.DATABASE_URL || "file:./prisma/dev.db",
    },
  },
});

export default prisma;
=======
// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { defineConfig } from "prisma/config";
import path from 'node:path';

const databaseUrl = `file:${path.resolve(process.cwd(), 'prisma', 'dev.db').replace(/\\/g, '/')}`;

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env.DATABASE_URL ?? databaseUrl,
  },
});
>>>>>>> master
